name: CI

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout example lab
        uses: actions/checkout@v2
        with:
          repository: cisc2200/example-lab
      - name: Checkout example testcases
        uses: actions/checkout@v2
        with:
          repository: cisc2200/example-tests
          path: tests
      - name: Run autograding
        uses: cisc2200/autograding@main
